---
- name: Deploying the PHP Applicaion to Dev Enviroment
  become: true
  hosts: todo

  tasks:
  
    - name: install httpd on the webserver
      ansible.builtin.apt:
        name: http
        state: present

    - name: ensure httpd is started and enabled
      ansible.builtin.service:
        name: http
        state: started 
        enabled: yes
      
    - name: install PHP
      ansible.builtin.apt:
      name={{ item }} update_cache=yes state=latest
      with_items:
          - php 
          - php-mysqlnd
          - php-gd 
          - php-curl
          - unzip
          - php-common
          - php-mbstring
          - php-opcache
          - php-intl
          - php-xml
          - php-fpm
          - php-json
    
    - name: ensure php-fpm is started and enabled
      ansible.builtin.service:
        name: php-fpm
        state: started 
        enabled: yes

    - name: Download the artifact
      get_url:
        url: http://3.237.72.80:8082/artifactory/PBL/php-todo
        dest: /home/ubuntu/
        url_username: admin
        url_password: 8*2rX7gKJNrp


    - name: unzip the artifacts
      ansible.builtin.unarchive:
       src: /home/ubuntu/php-todo
       dest: /home/ubuntu/
       remote_src: yes

    - name: deploy the code
      ansible.builtin.copy:
        src: /home/ubuntu/var/lib/jenkins/workspace/php-todo_main/
        dest: /var/www/html/
        force: yes
        remote_src: yes

    - name: remove nginx default page
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: restart http
      ansible.builtin.service:
        name: http
        state: restarted