[nfs]
  172.31.84.72 ansible_ssh_user='ec2-user'

[webservers]
 172.31.95.27 ansible_ssh_user='ec2-user'
 172.31.95.51 ansible_ssh_user='ec2-user'
  
[db]
172.31.90.239 ansible_ssh_user='ubuntu' 




