---
#- name: Include dynamic variables 
 # hosts: all

#- name: import common file
  #import_playbook: ../static-assignments/common.yml
  #tags:
    #- always

#  - hosts: artifactory
#  - name: artifactory assignmnet
#    ansible.builtin.import_playbook: ../static-assignments/artifactory.yml 

#- name: include env-vars file
  #import_playbook: ../dynamic-assignments/env-vars.yml
  #tags:
   # - always

- hosts: db
- name: db assignment
  ansible.builtin.import_playbook: ../static-assignments/db.yml

#- name: import webservers file
 # import_playbook: ../static-assignments/webservers.yml

# - name: import Loadbalancers assignment
#   import_playbook: ../static-assignments/lb.yml
#   when: load_balancer_is_required

# - hosts: jenkins
# - name: ansible mysql client
#   ansible.builtin.import_playbook: ../static-assignments/common.yml